#!/usr/bin/env bash

# Install nginx
# Nginx should be listening on port 80

sudo apt-get update -y
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'

echo "Hello, world!" | sudo tee /var/www/html/index.html

sudo service nginx restart
